POST http://localhost:5000/exams/add HTTP/1.1
Content-Type: application/json

{
    "title" : "Prova de Desenvolvimento Backend Jr 2",
    "questions" : [
        {
            "questionNumber" : 1,
            "questionData" : {
                "description" : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Baseado no trecho anterior, se você fosse escrever alternativas mockadas, como elas se pareceriam?",
                "options" : [
                    {"text" : "Eu sou a alternativa a", "value" : true},
                    {"text" : "Eu sou a alternativa b", "value" : false},
                    {"text" : "Eu sou a alternativa c", "value" : false}
                ]
            }},
        {
            "questionNumber" : 2,
            "questionData" : {
                "description" : "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Novamente, baseado nessas informações, responda: Qual é a melhor academia?",
                "options" : [
                    {"text" : "Gama Academy, obviamente", "value" : true},
                    {"text" : "A que tem um brofist verdinho", "value" : true},
                    {"text" : "A AMAG, que é Gama só que de trás pra frente.", "value" : true}
                ]
            }
        }
    ]

}